# 使用されているビルド使用スタンダートのバージョン0.2が最新
version: 0.2
# env:
#   variables:
#     AWS_DEFAULT_REGION: "ap-northeast-1"
#     DOCKER_USER: AWS
#     REPOSITORY_URI: "<ECRのURIをコピーする>"
#     IMAGE_NAME: <作成した>
# phasesにはあとinstallがある
phases:
  pre_build:
    commands:
      - echo "login ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo "start build"
      - docker build -t "$REPOSITORY_URI/$IMAGE_NAME:latest" .
  post_build:
    commands:
      - echo "push ECR"
      - docker push "$REPOSITORY_URI/$IMAGE_NAME:latest"
      # - printf '{"Version":"1.0","ImageURI":"%s"}' $REPOSITORY_URI/$IMAGE_NAME:$IMAGE_TAG > imageDetail.json
# artifacts:
#   files: imageDetail.json
